version: '3.7'
services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    environment:
      NODE_ENV: "development"
      DB_NAME: "api"
      DB_HOST: "db"
      DB_PASS: "root"
      DB_USER: "root"
    container_name: node-api
    volumes:
      # mount project folder
      - ./:/app
      # do not mount node_modules folder
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    #tty: true  
    command: npm run start:dev